# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Айдар Сафиуллин
title: Ruby on Rails разработчик
email: aidarinXT@mail.ru
phone: +7(986)925-42-25

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# telegram_username: Aidar_Safiullin
github_username:  safiullinaidar
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: aidar_r_safiullin
linkedin_username: Aidar Safiullin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/Aidar_Safiullin
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: О себе
about_profile_image: images/avatar.jpeg
about_content: | # this will include new lines to allow paragraphs
  Привет, меня зовут Айдар, мне 34 года, в течение 12 лет занимался промышленной автоматизацией, 
  а летом 2021 года решил заняться автоматизацией бизнесс-процессов на уровне информационных систем. 
  Чем глубже погружался, тем больше было желание заняться разработкой веб-приложений на интересном стеке.
  Мой выбор уже давно пал на <mark>Ruby</mark>, и вот уже более полугода я занимаюсь изучением фреймворка <mark>Ruby on Rails</mark>
  
  В июне 2022 года завершил интесив по Ryby on Rails в наиболее продвинутой онлайн школе по данному направлению в РФ - [Хороший программист](https://goodprogrammer.ru/). 
  В рамках обучения разрабатывал проекты, размещал на <mark>GitHub</mark>. Детали некоторых проектов указаны ниже.

  <u>Цель:</u>
  В данный момент нахожусь в поиске работы на позицию <mark>Ryby on Rails</mark> разработчика с возможностью развития.

  <u>Языки</u>

  Русский, Татарский - native
  
  Английский - upper-intermediate (B2)
  
  Итальянский - elementary (A1)

content:
  - title: Проекты
    layout: list
    content:
      - layout: top-middle
        title: "Шашлыки"
        link: https://shashlykmashlyk.herokuapp.com
        link_text: Шашлыки
        additional_links:
          - title:  barbeque
            icon: fab fa-github
            url: https://github.com/safiullinaidar/barbeque
        quote: >
          Приложение для создания событий
        description: |
          Приложение для создания событий (например, похода с друзьями на шашлыки). 
          События могут создавать зарегистрированные пользователи. 
          На событие можно подписаться (как авторизованному пользователю, так и анонимному), 
          оставить комментарий, добавить фотографии.
      - layout: top-middle
        title: "Askme"
        link: https://powerful-hollows-33867.herokuapp.com
        link_text: Askme
        additional_links:
          - title:  askme
            icon: fab fa-github
            url: https://github.com/safiullinaidar/askme
        quote: >
          Приложение, в котором можно задавать вопросы и получать на них ответы
        description: |
          Функционал веб-приложения аналогичен известному сайту Ask.fm. 
          Для использования приложения необходимо в нём зарегистрироваться. 
          После этого можно редактировать свой профиль, задавать и отвечать 
          на вопросы как зарегистрированных, так и анонимных пользователей.

  - title: Навыки
    layout: text
    content: |
      <b>Основы</b>

      Понимаю приципы <mark>ООП</mark>, <mark>DRY</mark>, <mark>SOLID</mark>, использую подходы по проектированию приложений, изучил паттерны программирования, 
      использую различные форматы данных (<mark>XML</mark>, <mark>JSON</mark>), использую реляционные БД (<mark>SQLite</mark>, <mark>PostgreSQL</mark>)

      <b>Ruby</b>

      Соблюдаю кодстайл, понимаю и использую основы синтаксиса, покрываю код тестами (<mark>RSpec</mark>), 
      использую интерактивную консоль, применяю библиотеки <mark>Rubygems</mark>

      <b>Инструменты</b>

      Уверенный пользователь ОС <mark>Linux Ubuntu</mark>, использую терминал, применяю <mark>Git</mark>, пушу проекты на удалённые репозитории <mark>GitHub</mark>, 
      осовил деплой на <mark>Heroku</mark>, отлаживаю код при помощи гема <mark>Debugger</mark>, деплой на <mark>VPS</mark> с применением гема <mark>Capistrano</mark>

      <b>Frontend</b>

      Понимаю суть протокола <mark>HTTP</mark>; осовил основы веб-дизайна, вёрстки; пишу на языке <mark>HTML5</mark>; применяю стили <mark>CSS3</mark>; 
      использую фронтэнд-фреймворки <mark>Bootstrap 5</mark>, <mark>Skeleton</mark>; применял некоторые модули, написанные на <mark>JS</mark>

      <b>Rails</b>

      Понимаю и применяю паттерн <mark>MVC</mark>, изучил структуру файлов проекта, понимаю и применяю соглашение <mark>REST</mark>, 
      понимаю и применяю основные подходы в проектировании <mark>Rails</mark>-приложений, применяю популярные гемы 
      (<mark>I18n</mark>, <mark>RSpec</mark>, <mark>Devise</mark>, <mark>Carrierwave</mark>, <mark>Mailjet</mark> и др.), 
      применяю принципы обеспечения безопасности <mark>Rails</mark>-приложений 
      (<mark>CSRF</mark>-токен, защита от <mark>SQL</mark>-инъекций, защита от спама, защита при авторизации), управляю фоновыми задачами при помощи <mark>ActiveJob</mark>

  - title: Опыт работы
    layout: list
    content:
      - layout: left
        title: АО "Сетевая компания"
        link: https://gridcom-rt.ru
        sub_title: Главный специалист — руководитель проекта Проектного офиса
        caption: Июль 2021 - настоящее время
        quote: >
           
        description: |
          Руководство проектами внедрения и развития информационных систем. Формирование технического задания, календарное планирование, 
          анализ бинес-требований функционального заказчика, управление командой проекта и ресурсами подрядных организаций. 
          Оценка эффективности хода реализации проекта по формализованным критериям. 
          Организация испытаний, опытной эксплуатации и окончательной приёмки систем.
      - layout: left
        title: ООО "ТатАвтоматизация"
        link: https://tatintec.ru
        sub_title: Заместитель главного инженера — начальник отдела исполнения контрактов, Главный специалист, Ведущий инженер, Инженер в ГК "Татинтек" (г. Альметьевск)
        caption: Октябрь 2009 - Июль 2021
        quote: >
           
        description: |
          Руководство сервисной деятельностью компании, формирование и поддрежка каталога услуг. 
          Организация взаимодействия с заказчиками. Непосредственное участие в стратегическом планировании, 
          разработка и контроль исполнения KPI всех руководителей. 
          Участие в проектном управлении, в формировании технической политики предприятия.

  - title: Образование
    layout: list
    content:
      - layout: left
        title: Альметьевский государственный нефтяной институт
        caption: 2004 - 2009
        sub_title: Автоматизация технологических процессов и производств (специалитет)
        quote: >
          Основан в 1952 году, ключевой ВУЗ в сфере подготвки кадров для нефтяной промышленности Республики Татарстан
        description: |
          Во время обучения в АГНИ я получил фундаметальное техническое образование, обучился подходам и методикам обучения,
          научился работать в команде. Это послужило мощным основанием для моей карьеры в сфере автоматизации и позволило мне
          совершенствовать свои знания в дальнейшем.

          В свободное время принимал участие в художественной самодеятельности.
      - layout: left
        title: Казанский (Приволжский) федеральный университет
        caption: Декабрь 2017 - Октябрь 2018
        sub_title: Программа профессиональной переподготовки управленческих кадров (Менеджмент)
        quote: >
          Основан в 1804 году, один из старейших ВУЗов в государстве, в стенах которого обучалось и работало множество выдающихся учёных, деятелей искусства, политиков
        description: |
          В КФУ я совершенствовал свои управленческие навыки, полученные в ходе карьеры. Также значительно
          "прокачал" свои "soft skills".
      - layout: left
        title: Хороший программист
        caption: Февраль 2022 - Июнь 2022
        sub_title: Онлайн интенсив по Ruby on Rails
        quote: > 
          Это лучшее, что может случиться с теми, кто ищет курсы по веб-разработке
        description: |
          Здесь я приобрёл навыки веб-разработчика, освоил методику работы с документацией и поиска информации для решения конкретных задач на проекте, 
          навыки работы в команде в сжатые сроки, под высокой нагрузкой. Подробнее обо всех приобретённых здесь навыках указано в специальном разделе "Наывки"
          
  - title: Ещё немного о себе
    layout: text
    content: |
      Наряду с интересом к веб-разработке вот ещё некоторые мои увлечения:
      - игра на гитаре;
      - караоке;
      - туризм;
      - командные интеллектуальные игры.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
